[[constraint]]
  name = "github.com/gobeat/interfaces"
  version = "~1.0.x"

[[constraint]]
  name = "github.com/gobeat/tools"
  version = "~1.0.x"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "~1.2"

[prune]
  go-tests = true
  unused-packages = true
